### ISSUE TITLE
1 error

### ISSUE THREAD

**Issue by PikachuLuke5** [ThinkingStudios/textrues-embeddium-options#12]
forge 1.20.1:
![Screenshot 2024-08-30 154933](https://github.com/user-attachments/assets/b4ed1adc-dff3-422b-9e0a-27120ef12ff7)

**Comment by CDWimmer** [comment]
I've found that Embeddium 0.3.9 works with the latest textrues available for 1.20.1

**Comment by TexBlock** [comment]
**Embeddium has merged RSO in 1.20.1 and above**, which means that you don't need to install TEO to use the similar video options screen.
