### ISSUE TITLE
textrue's embeddium options 0.0.0

### ISSUE THREAD

**Issue by kINGGJORGE** [ThinkingStudios/textrues-embeddium-options#14]
i keep getting an error message that i need to be on textrue's embeddium options 0.0.0 but there is no version like that i have alredy deleted and reinstalled the modoack could someone help me

**Comment by TexBlock** [comment]
**Embeddium has merged RSO in 1.20.1 and above**, which means that you don't need to install TEO to use the similar video options screen.
