### ISSUE TITLE
Video settings menu option crashes game with latest Embeddium

### ISSUE THREAD

**Issue by DJBaphomet** [ThinkingStudios/textrues-embeddium-options#4]
Game entirely closes when trying to open the Video Settings tab in options menu, works fine when disabling this mod or when downgrading Embeddium to version 0.2.18

**Versions**
- Embeddium 0.3.0
- TexTrue's Embeddium Options 0.1.3
- Minecraft 1.20.1

**Crash Log**
- [latest.log](https://mclo.gs/d2Pe80v)
- [crash-report log](https://mclo.gs/96Jwzps)

**Comment by TexBlock** [comment]
I'll be releasing a new version to fix this later on.

**Comment by ROTCTHSPECIAL** [comment]
> I'll be releasing a new version to fix this later on.

yea this happen to me too with lastest verison
