### ISSUE TITLE
Causes crashes when used with the newest Embeddium.

### ISSUE THREAD

**Issue by 123qwqeq** [ThinkingStudios/textrues-embeddium-options#5]
Embeddium  0.3.0
TexTrue's Embeddium Options 0.1.3
game 1.20.1
[crash-2024-01-30_17.59.08-client.txt](https://github.com/ThinkingStudios/textrues-embeddium-options/files/14096002/crash-2024-01-30_17.59.08-client.txt)

**Comment by TexBlock** [comment]
I'll be releasing a new version to fix this later on.
