### ISSUE TITLE
Donation prompt message is unmodified from Sodium

### ISSUE THREAD

**Issue by embeddedt** [ThinkingStudios/textrues-embeddium-options#6]
Currently, the `DONATION_PROMPT_MESSAGE` list in `SodiumVideoOptionsScreen` uses the same message as upstream, rather than Embeddium's [reworded variant](https://github.com/embeddedt/embeddium/blob/abf0fe6f682059f927c3314d1730dd7b5cd048f3/src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumOptionsGUI.java#L429-L435), that more clearly distinguishes the two mods. I believe this will lead to a different message being shown with TEO installed v.s. without.

**Comment by TexBlock** [comment]
I'll change the text to match Embeddium later on

**Comment by TexBlock** [comment]
fixed in `0.1.2+mc1.20.4` and `0.1.5+mc1.20.1`.
