### ISSUE TITLE
IT'S KEEP CRASHING WITH 1.20.1

### ISSUE THREAD

**Issue by ROTCTHSPECIAL** [ThinkingStudios/textrues-embeddium-options#7]
Video settings menu option or Join The World crashes game

I try to downgrade "Embeddium verison 0.3.1+mc1.20.4" for "TexTrue's Embeddium Options verison 0.1.5+mc1.20.1"

Crash log :
[crash-2024-03-23_22.38.31-client.txt](https://github.com/embeddedt/embeddium/files/14732078/crash-2024-03-23_22.38.31-client.txt)

Lastes log :
[latest.log](https://github.com/embeddedt/embeddium/files/14732079/latest.log)

**Comment by TexBlock** [comment]
TextruesEmbeddiumOptions or TextruesRubidiumOptions?

![image](https://github.com/ThinkingStudios/textrues-embeddium-options/assets/65154269/42e79c27-0b86-433b-866d-db8eadcf6cb1)

**Comment by ROTCTHSPECIAL** [comment]
> TextruesEmbeddiumOptions or TextruesRubidiumOptions?
> 
> ![image](https://private-user-images.githubusercontent.com/65154269/316253828-42e79c27-0b86-433b-866d-db8eadcf6cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTEwMjYsIm5iZiI6MTcxMTIxMDcyNiwicGF0aCI6Ii82NTE1NDI2OS8zMTYyNTM4MjgtNDJlNzljMjctMGI4Ni00MzNiLTg2NmQtZGI4ZWFkY2Y2Y2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE2MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MTllZDc3YmRkMzZjYjRjMmZlMGQzOGQ5ZTgyOTU1NGU2M2JlMTFkMzE5NTAzODNlMDM3ZGFmMDI3YWYwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CgQwO5DgEldvKd44Fc9VocFx260hoDKkZVrDpRPDjW4)

Ok my fail it's TextruesRubidiumOptions but the main it's work fine with TextruesRubidiumOptions I will try it with TextruesEmbeddiumOptions

**Comment by ROTCTHSPECIAL** [comment]
> TextruesEmbeddiumOptions or TextruesRubidiumOptions?
> 
> ![image](https://private-user-images.githubusercontent.com/65154269/316253828-42e79c27-0b86-433b-866d-db8eadcf6cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTEwMjYsIm5iZiI6MTcxMTIxMDcyNiwicGF0aCI6Ii82NTE1NDI2OS8zMTYyNTM4MjgtNDJlNzljMjctMGI4Ni00MzNiLTg2NmQtZGI4ZWFkY2Y2Y2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE2MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MTllZDc3YmRkMzZjYjRjMmZlMGQzOGQ5ZTgyOTU1NGU2M2JlMTFkMzE5NTAzODNlMDM3ZGFmMDI3YWYwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CgQwO5DgEldvKd44Fc9VocFx260hoDKkZVrDpRPDjW4)

 here you are
 
[crash-2024-03-23_23.24.54-client.txt](https://github.com/ThinkingStudios/textrues-embeddium-options/files/14732902/crash-2024-03-23_23.24.54-client.txt)

[latest.log](https://github.com/ThinkingStudios/textrues-embeddium-options/files/14732901/latest.log)

**Comment by TexBlock** [comment]
This is a crash caused by dynamiclightsreforged, and you can use RyoamicLight instead
