### ISSUE TITLE
Compatibility Problem with Embeddium 0.3.16 and above

### ISSUE THREAD

**Issue by Chiller2019** [ThinkingStudios/textrues-embeddium-options#9]
Hey,

the new Embeddium-Version 0.3.17 (Release: 1.05.2024) for MC1.20.1 is not compatible with TexTrue's Embeddium Options 0.1.5.
![grafik](https://github.com/ThinkingStudios/textrues-embeddium-options/assets/50303399/77099496-7325-47ec-95b1-5f6eb74788a9)

Kind regards

**Comment by SireAwfulThe1st** [comment]
Yep, having the same issues too, I'd just write smth here instead of making a same issue tae prevent spam.

**Comment by TexBlock** [comment]
see https://github.com/embeddedt/embeddium/issues/276

> [Embeddium 0.3.16 changelog](https://github.com/embeddedt/embeddium/wiki/Changelog#0316):
> The main changes in this release are our new config screen and improved performance when using the experimental Forge light pipeline.
> 
> Note: This release **replaces TexTrue's Embeddium Options (on Forge) and Reese's Sodium Options (on Fabric)**. The game will **not launch with either of these installed**, to avoid unexpected compatibility issues.

It looks like Embeddium has merged RSO, which means that you don't need to install TEO to use the similar video config screen. I may archive this mod in the future.

**Comment by xu-sa** [comment]
i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this

**Comment by TexBlock** [comment]
I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.

**Comment by TexBlock** [comment]
> i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this

I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.

**Comment by xu-sa** [comment]
> > i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this
> 
> I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.

MY BAD sorry iv sovled this problem now, thanks

**Comment by Kondr654321** [comment]
и чё делать?

**Comment by Linkspeedrunner** [comment]
embeddium extras need TEO to work
[latest.log](https://github.com/user-attachments/files/16514084/latest.log)

**Comment by RakkenTi** [comment]
Yep ^

**Comment by bee4bee** [comment]
> > i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this
> 
> I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.

That's where you're wrong. If you delete 
TexTrue's Embeddium Options, then minecraft will give an error that it is missing this mod.
![image](https://github.com/user-attachments/assets/4690a70e-db4c-4705-b2c1-554b1d3cd702)

**Comment by Yaen11** [comment]
> Hey,
> 
> the new Embeddium-Version 0.3.17 (Release: 1.05.2024) for MC1.20.1 is not compatible with TexTrue's Embeddium Options 0.1.5. ![grafik](https://github.com/ThinkingStudios/textrues-embeddium-options/assets/50303399/77099496-7325-47ec-95b1-5f6eb74788a9)
> 
> Kind regards

what did you do to fix it?

**Comment by Yaen11** [comment]
> > > i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this
> > 
> > 
> > I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.
> 
> That's where you're wrong. If you delete TexTrue's Embeddium Options, then minecraft will give an error that it is missing this mod. ![image](https://github.com/user-attachments/assets/4690a70e-db4c-4705-b2c1-554b1d3cd702)

what did you do to fix it?

**Comment by Yaen11** [comment]
> embeddium extras need TEO to work [latest.log](https://github.com/user-attachments/files/16514084/latest.log)

??What is TEO, can you explain it to me? I need help

**Comment by Yaen11** [comment]
> > > i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this
> > 
> > 
> > I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.
> 
> MY BAD sorry iv sovled this problem now, thanks

What did you do to fix it?

**Comment by 37283721** [comment]
Please help me :(

I've tried everything, nothing helps. I still have this error "<bdi class="Box-sc-g0xbh4-0 lhNOUb markdown-title">Mod embeddium only supports 'textrues_embeddium_options' 0.0.0-NOT-COMPATABLE Currently, 'textrues_embeddium_options' is 0.1.5+mc1.20.1"

**Comment by TexBlock** [comment]
> Please help me :(
> 
> I've tried everything, nothing helps. I still have this error "Mod embeddium only supports 'textrues_embeddium_options' 0.0.0-NOT-COMPATABLE Currently, 'textrues_embeddium_options' is 0.1.5+mc1.20.1"

Embeddium has merged RSO in 1.20.1 and above, which means that you don't need to install TEO to use the similar video options screen.

**Comment by jaaj5839** [comment]
> > Please help me :(
> > I've tried everything, nothing helps. I still have this error "Mod embeddium only supports 'textrues_embeddium_options' 0.0.0-NOT-COMPATABLE Currently, 'textrues_embeddium_options' is 0.1.5+mc1.20.1"
> 
> Embeddium has merged RSO in 1.20.1 and above, which means that you don't need to install TEO to use the similar video options screen.

But when i delete TEO the game crashes

**Comment by KatsuMouley** [comment]
> > > > i have this Issue too, does it mean Embeddium not support TEO in higher version?how to Solve this
> > > 
> > > 
> > > I think I made it pretty clear that Embeddium already includes TEO in version 1.20.1 and above.
> > 
> > 
> > That's where you're wrong. If you delete TexTrue's Embeddium Options, then minecraft will give an error that it is missing this mod. ![image](https://github.com/user-attachments/assets/4690a70e-db4c-4705-b2c1-554b1d3cd702)
> 
> what did you do to fix it?

I believe that if you just remove EmbeddiumExtras it will work

**Comment by Lorddippy12** [comment]
I have this problem, and when I delete TEO, my game crashes every time I launch. Somone please help me. idk what to do.

**Comment by snegovik097** [comment]
![Image](https://github.com/user-attachments/assets/781e27cf-4317-4d2a-a942-5c32ed7adb13)
Я выключил эти 2 мода и обновил Embadium до нудной версии
===
I turned off these 2 mods and updated Embadium to the required version.
